apiVersion: v1
kind: Pod
metadata: 
  name: my-app
  labels:
    name: my-app
    app: demo-my-app

spec:
  containers:
    name: my-app
    image: docker pull gcr.io/dv-michael-olaleye-1/helloworld-image:latest
    ports:
      containerPort: 80